Class {
	#name : #SKStackBlockConnection,
	#superclass : #AnObsoleteSKBlockConnection,
	#category : #'SqueakKara-Core'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'SLH 6/2/2026 21:49'
}
SKStackBlockConnection >> anchorPoint [

	^ self center
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'SLH 6/2/2026 22:40'
}
SKStackBlockConnection >> minExtent [

	^ 0@0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'SLH 6/2/2026 22:40'
}
SKStackBlockConnection >> minHeight [

	^ 0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'SLH 6/2/2026 22:40'
}
SKStackBlockConnection >> minWidth [

	^ 0
]
