Class {
	#name : #SKProgrammingUI,
	#superclass : #SystemWindow,
	#category : #'SqueakKara-Core'
}

{
	#category : #interface,
	#'squeak_changestamp' : 'Lars Kuhr 5/20/2026 08:53'
}
SKProgrammingUI >> close [

	self subclassResponsibility
]

{
	#category : #interface,
	#'squeak_changestamp' : 'Lars Kuhr 5/20/2026 08:53'
}
SKProgrammingUI >> getCode [

	self subclassResponsibility
]

{
	#category : #interface,
	#'squeak_changestamp' : 'Lars Kuhr 5/20/2026 08:53'
}
SKProgrammingUI >> open [

	self subclassResponsibility
]
