Class {
	#name : #SKProgrammingUIMealy,
	#superclass : #SKProgrammingUI,
	#category : #'SqueakKara-Core'
}

{
	#category : #actions,
	#'squeak_changestamp' : 'Lars Kuhr 5/27/2026 11:44'
}
SKProgrammingUIMealy >> build [

	SKStateMachineEditor new 
]

{
	#category : #actions,
	#'squeak_changestamp' : 'Lars Kuhr 5/27/2026 11:40'
}
SKProgrammingUIMealy >> getCode [

	^ ''
]

{
	#category : #actions,
	#'squeak_changestamp' : 'Lars Kuhr 5/27/2026 11:40'
}
SKProgrammingUIMealy >> setCode: aCode [

	
]
